### PR TITLE
Joe Warren attendance

### PR DESCRIPTION
**Pull request by MightyJoeW**

### CODE REVIEW

**Comment by m2mathew** [comment]
Hey, @MightyJoeW, resolve the conflicts and I can merge. BUT let's leave the single quotes as the way we do business here. Should probably install a linter. 😄

**Comment by MightyJoeW** [comment]
Okay thanks, I'll resolve it. And I have a few extensions turned on (I
think prettier is adding the double quotes). I'll disable that.

On Dec 12, 2017 8:36 PM, "Mike Mathew" <notifications@github.com> wrote:

Hey, @MightyJoeW <https://github.com/mightyjoew>, resolve the conflicts and
I can merge. BUT let's leave the single quotes as the way we do business
here. Should probably install a linter. 😄

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/m2mathew/meetup-metrics/pull/5#issuecomment-351263481>,
or mute the thread

**Comment by m2mathew** [comment]
I will reopen this. You can leave a PR open even with conflicts, no worries. Your changes **are** wanted!

**Comment by m2mathew** [comment]
Closed in favor of #20

**Pull request closed without merging**
